### ISSUE TITLE
Unable to add certain podcast feeds, certificate error - v6.1

### ISSUE THREAD

**Issue by afxgit** [Libresonic/libresonic#370] opened 2017-04-28 12:13 UTC
Example podcast feed url:
https://latenightlinux.com/feed/mp3

When adding some podcast feeds they're failing to add properly and I see the following error
    Error hostname in certificate didn't match: != OR OR

If I check a podcast download link on their actual page the audio is delivered from http://podtrac.com/pts/redirect.mp3/latenightlinux.com/media/LNL09.mp3 so assuming this is the issue - can the certificate issue be ignored somehow for content delivered like this? I imagine there are a number of sites that used podtrac for stats/delivery

Thanks!

**Comment by mdecker** [comment] 2017-04-30 08:14
Please check against the 6.2 betas. I have seen this problem in 6.1 and earlier as well. It should be fixed now.
It was caused by old SSL code that did not check new certificate properties correctly as far as I could tell.

**Comment by jooola** [comment] 2017-05-12 00:38
Does this issue has been fixed by upgrading libresonic ?

**Comment by mdecker** [comment] 2017-05-12 10:42
I vote for closing it as the OP does not seem to be actively participating. It can be reopened if the problem persists but as far as I can tell 6.2 fixes this (see above).

**Closed** 2017-05-12 11:21 UTC
Labels: issue

**Comment by pfaffman** [comment] 2017-09-02 16:23
Is there a place that a Normal Person can download a 6.2 binary? If this bug was squashed in May, why can't I get a version without it in August?

**Comment by jooola** [comment] 2017-09-02 17:08
@pfaffman See [here](https://github.com/airsonic/airsonic/blob/master/README.md#history)
Or the quick answer here : https://airsonic.github.io/download/

**Comment by pfaffman** [comment] 2017-09-05 17:44
Oh. Sigh. Indeed I missed a memo. Or two. Thanks for the explanation.
