### ISSUE TITLE
Arbitrary frontend reloads

### ISSUE THREAD

**Issue by vestingz** [Libresonic/libresonic#113] opened 2016-07-19 19:13 UTC
The home view (and possibly all other views, too) automatically refresh every ~30secs with no apparent reason. Especially in random view this has the annoying effect of an ever changing order of albums.

**Comment by csobsidian** [comment] 2016-07-19 19:30
I believe that was default behavior of Subsonic.

**Comment by vestingz** [comment] 2016-07-19 19:33
Any way to disable this? It's quite annoying, especially when browsing the random section.

**Comment by EugeneKay** [comment] 2016-07-19 19:55
This is controlled/caused by this line: https://github.com/Libresonic/libresonic/blob/develop/libresonic-main/src/main/webapp/WEB-INF/jsp/home.jsp#L10

I would welcome a PR to add a Setting for this value(or "0" to disable auto-refresh).

**Comment by fxthomas** [comment] 2016-07-19 20:57
Ha, this one actually annoyed me a few times. Since I already did something very similar in another PR, I added #115 to fix that. Feel free to test/comment.

**Comment by vestingz** [comment] 2016-07-19 21:20
Kool :) Will test as soon as i find time. Thank you!

**Comment by fxthomas** [comment] 2016-07-19 21:30
Note that it includes a change in the database schema, so it's probably not a good idea to test it on your production database! (But nobody does that, right? :smiling_imp: )

**Comment by vestingz** [comment] 2016-07-19 21:53
Ugh, good to know :)

**Comment by zifnab06** [comment] 2016-11-27 21:11
Fixed by #115, going to close this now.

**Closed by zifnab06** 2016-11-27 21:11 UTC
Labels: change, enhancement
