### ISSUE TITLE
non-roman music file name not displayed in libresonic

### ISSUE THREAD

**Issue by lilarcor** [Libresonic/libresonic#170] opened 2016-12-08 08:06 UTC
using 6.1 in freenas, 9.10, container freebsd10, tomcat 8, followed 6.1 installation guideline

**Comment by fxthomas** [comment] 2016-12-08 20:52
Can you post a screenshot? Is your browser able to display those non-roman characters in other websites?

**Comment by lilarcor** [comment] 2016-12-09 01:08
![clipboard03](https://cloud.githubusercontent.com/assets/9455380/21033860/b65a14fa-bdee-11e6-8486-2598f3dec650.jpg)
attached please find the screenshot. Both are using same music library. Left is using subsonic/madsonic  6.0 ,right one is libresonic 6.1. Seems libresonic just skip the music file with non-Roman name.

**Comment by lilarcor** [comment] 2016-12-09 02:41
i think it's a tomcat problem, libresonic can show chinese correctly when i set the UI to Chinese. Do you have any idea for adjust some setting in tomcat. I tried to add URIEncoding="UTF-8" in server.xml, but not working. So far, there is no other format installation package, so I don't know how to deal with it.

**Comment by lilarcor** [comment] 2016-12-09 06:58
![clipboard01](https://cloud.githubusercontent.com/assets/9455380/21040414/bda92e54-be1f-11e6-8d19-826d5df3bd24.jpg)

I redeploy the 6.1 war file, and made more tests. I think the problem is still in war but not in tomcat8. I found non-roman path is ignored, but non-roman music file in roman path was added into the library , and they are not shown correctly.

**Comment by lilarcor** [comment] 2016-12-09 09:53
![clipboard01](https://cloud.githubusercontent.com/assets/9455380/21044636/f0c75190-be37-11e6-8e3d-8dbf71180a0f.jpg)
sorry for the flooding. Above picture shows the music with Chinese, those Chinese characters are from music ID3 tag, their original files names  are in English.
So followings are what I got:
1. broswer can show chinese characters
2. libresonic skipped scanning non-roman folder
3.libresonic will add non-roman file into db, but not shown correctly in UI

**Comment by fxthomas** [comment] 2016-12-09 10:16
FYI about half my library has non-roman characters (Chinese, Japanese, Korean and Russian off the top of my head) and I've never had any issues. So the issue is probably somewhere between the Libresonic WAR and Tomcat. That said, I'm running Jetty so I won't be of much help.

Are there any errors in the logs? Permission issues? What's the locale Tomcat is running under? What's the OS, both client and server? Java versions?

**Comment by lilarcor** [comment] 2016-12-09 10:18
Version	6.1 – November 27, 2016
Server	Apache Tomcat/8.0.39, java 1.8.0_112, FreeBSD (249.4 MB / 848.0 MB)
I am running it under freenas jail, FreeBSD-10.3-stable

**Comment by lilarcor** [comment] 2016-12-09 15:15
just an update. I give up setting it up on a jail in freenas, I set it up in Debian8, runs very well.

thanks for help anyway

**Comment by muff1nman** [comment] 2016-12-12 03:41
Closing, but let us know if you run into this again on Debian.

**Closed by muff1nman** 2016-12-12 03:41 UTC

**Comment by jooola** [comment] 2017-03-11 12:30
Maybe related to #135
