### ISSUE TITLE
Migrate to SpringBoot

### ISSUE THREAD

**Issue by biconou** [Libresonic/libresonic#142] opened 2016-11-19 10:42 UTC
I started to work on a migration to SpringBoot.
The main benefits of that are 

- easily package the application as an executable jar embedding Tomcat
- simplify pom and dependencies management
- standardization
- upgrade to Spring 4 

@muff1nman 
As it is a significantly hard work, can you confirm it is worth it and the PR has a chance to be merge if it works fine ?
PS. I am continuing the work you started on the upgrade to Spring 4.

**Comment by muff1nman** [comment] 2016-11-19 17:15
So I think it might make sense to get spring 3 and 4 working first before doing this so as to split the effort into more manageable chunks. I'm very close on getting spring 3 working which is a step in the right direction (I have to fix the login error message). I think if we worked together on spring3 then 4 then we can get spring boot going. Does that sound reasonable? The smaller we can keep these PRs the easier it is to test and merge them.

**Comment by biconou** [comment] 2016-11-19 18:25
@muff1nman You are perfectly right. 
I will begin to work on the new PR #143 you just created.

**Comment by EugeneKay** [comment] 2016-11-27 22:32
I have made this into a Goal for the 6.2 release. I would like to see the legacy subsonic-booter completely removed and replaced with Spring Boot. Let me know if this is too ambitious and should be pushed further back to Future.

**Comment by biconou** [comment] 2016-11-27 22:37
I think it should be in the 6.2.
Subsonic-booter is definitely messy.

**Comment by biconou** [comment] 2016-12-12 21:36
I started the SpringBoot port. The application builds and starts well be the main difficulty is that I think the hole security configuration must be rewritten using java style configuration. I must investigate hard.

**Comment by biconou** [comment] 2017-01-01 18:28
The Spring Boot PR is ready to be merged. It is reasonably stable.  
Even if there is still things to be done. 

I think we must have a discussion on the final packaging we want. 
For the moment, libresonic-main produces 
- a libresonic.war standalone package
- a traditionnal war called libresonic.war.original

To start libresonic for development, just run spring-boot:run.

**Comment by EugeneKay** [comment] 2017-01-01 21:10
I have merged #176.

@biconou Do you think its time for a 6.2.beta0 tag to try it out, or do you want to wait until the standalone installable targets(rpm/deb/etc) have been reworked to use SpringBoot?

**Comment by biconou** [comment] 2017-01-01 21:52
I think we could wait because some clean up must be done and a minimum documentation too.

**Comment by fxthomas** [comment] 2017-01-03 21:12
I managed to fiddle with the startup script enough to get it to work. One thing that bugs me is that it feels significantly slower than when using the booter JAR. Some hard numbers :

* Startup time went from 25-30 seconds to 50 seconds
* HTTP request for an album page (`main.view?id=xxxx`) went from ~100ms to 2 seconds

I just ran the server with the command below, is there anything else I should have done?

```bash
exec ${JAVA} -Xmx${LIBRESONIC_MAX_MEMORY}m \
  -Dserver.host=${LIBRESONIC_HOST} \
  -Dserver.port=${LIBRESONIC_PORT} \
  -Dserver.contextPath=${LIBRESONIC_CONTEXT_PATH} \
  -Dlibresonic.home=${LIBRESONIC_HOME} \
  -Dlibresonic.host=${LIBRESONIC_HOST} \
  -Dlibresonic.port=${LIBRESONIC_PORT} \
  -Dlibresonic.httpsPort=${LIBRESONIC_HTTPS_PORT} \
  -Dlibresonic.contextPath=${LIBRESONIC_CONTEXT_PATH} \
  -Dlibresonic.defaultMusicFolder=${LIBRESONIC_DEFAULT_MUSIC_FOLDER} \
  -Dlibresonic.defaultPodcastFolder=${LIBRESONIC_DEFAULT_PODCAST_FOLDER} \
  -Dlibresonic.defaultPlaylistFolder=${LIBRESONIC_DEFAULT_PLAYLIST_FOLDER} \
  -Djava.awt.headless=true \
  -verbose:gc \
  -jar libresonic.war
```

**Comment by biconou** [comment] 2017-01-03 21:26
The startup time is longueur, that's not surprising me but is that so important ? 
But the slower http request is annoying. It should not.
I would be interested in doing a comparison benchmark between stable and develop branch using jmeter or something.
If you are wright, the difference between 100ms and 2s is so huge that there must be a clear and fixable reason. 

Is anybody here very clever with load and performance testing ?
@fxthomas what do you include in the 2s time ? both client and server elapsed time ?

**Comment by fxthomas** [comment] 2017-01-03 21:41
The 2s time is the full request time, including client. I'll try to investigate more.

The startup time is not that important, I am just not used to web servers taking nearly a minute to fully load, so I thought something must have been wrong somewhere.

**Comment by fxthomas** [comment] 2017-01-03 21:44
Just a not, I am getting a lot of messages like this that didn't happen before, but they are probably harmless?

```
Jan 03 22:43:48 libresonic.sh[20588]: 2017-01-03 22:43:48.432  WARN 20588 --- [ost-startStop-1] org.apache.catalina.webresources.Cache   : Unable to add the resource at [/WEB-INF/lib/spring-security-web-4.1.3.RELEASE.jar] to the cache because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache
```

**Comment by biconou** [comment] 2017-01-03 21:46
Here is the startup time I get launching spring-boot:run from IntelliJ. (system debian on a 5 years old computer).

Started Application in 27.513 seconds

**Comment by biconou** [comment] 2017-01-03 21:47
try to remove -verbose:gc 
and what is your -Xmx${LIBRESONIC_MAX_MEMORY}m ?

You could also open a jconsole.

**Comment by biconou** [comment] 2017-01-03 21:49
There are also stack traces on the startup that need to be fixed.

**Comment by fxthomas** [comment] 2017-01-03 22:14
Increasing `-Xmx` to 200MB did nothing at all.

But thanks for the JConsole pointer, I did not know it existed. Before/after we have twice as much heap usage (from ~70MB before Spring Boot to ~155MB) but roughly the same number of loaded classes and threads.

Not sure what else I should be looking at though. Is there any difference between Jetty (libresonic-booter) and Tomcat (the default in Spring Boot)?

**Comment by muff1nman** [comment] 2017-01-03 22:44
Could we perhaps use maven profiles to separate the tomcat war from the spring boot stuff? I've done this in previous projects and it's worked well.

**Comment by fxthomas** [comment] 2017-01-03 22:56
@biconou I finally increased `-Xmx` to 400MB and ruled out network issues by bypassing my Nginx proxy and using a single authenticated cURL request to one `main.view?id=xxxx`.

Results are really random : after Spring Boot timings are sometimes as good as before but most of the time take 2 or 3 more seconds. Before it, they were consistently at ~100ms. This smells like a GC issue, but I am a bit lost as to where to go now.

I can reproduce that on any album in my collection (just go to home and click on an album), and the timings show up in the "Network" tab in Firefox's dev tools.

**Comment by biconou** [comment] 2017-01-04 00:03
Ok, that will need to be investigated. 
May be that could be due to some issue with the coverart cache ?

**Comment by biconou** [comment] 2017-01-04 00:08
@muff1nman I think that sounds fine especially if you got a good recipe. I can't figure out how to do that. 
Perhaps we could also avoid having a too complex pom.

**Comment by fxthomas** [comment] 2017-01-04 19:35
@biconou Using VisualVM I was able to profile the running web server (after startup and a few requests so that I don't accidentally profile a starting process) :

![scrn_tomcat_profile_libresonic](https://cloud.githubusercontent.com/assets/613594/21656105/f57bad5a-d2bc-11e6-80a0-27df50d2f7f6.png)


One thing I noticed after looking at this was that Tomcat did not (unlike Jetty) extract the whole WAR at startup. I don't have a very fast CPU, so my hypothesis is that the slowdowns are caused by Tomcat reading and uncompressing data out of the WAR on each request. Does that make sense?

Do you know of some tool that can profile individual HTTP requests so that I can confirm that this is indeed the culprit?

Alternatively, there's an `unpackWARs` setting described [here](http://docs.spring.io/s2-dmserver/2.0.x/user-guide/html/ch09s03.html), but I wasn't able to find out how to add this to the embedded container in the Libresonic WAR.

**Comment by biconou** [comment] 2017-01-04 20:32
That might be interesting.
http://stackoverflow.com/questions/40319869/spring-boot-embedded-tomcat-performance
@muff1nman is on the way to make libresonic working again on tomcat. After that we will be able to compare both solutions.

**Comment by biconou** [comment] 2017-01-04 20:45
@fxthomas I got few free time left these days so I just ran a couple of searches on google. I can't really find any evident issue on Spring Boot application performance. 
But performance is a very important concern and we will have to find out what happens to your own environment. 
We will also can try replacing embedded Tomcat by jetty. 
Finally I am thinking of including performance metrics inside the application using the Metrics framework I introduced for unit testing. 
I am seeking other ideas.

**Comment by fxthomas** [comment] 2017-01-08 14:03
Testing the new commits right now.

By the way, is there a reason commit e9697fb4 added a `/` in the login form's `action` parameter in `login.jsp`? I'm not using Libresonic under the root context path, and this breaks login for me. Removing the `/` makes it work again.

**Comment by fxthomas** [comment] 2017-01-08 14:54
Nevermind with the login form, it was fixed later. However something broke in the migrations because all my music and users were gone from Libresonic after upgrading to the latest commit.

They were still visible in the HSQLDB console outside of Libresonic, and the only warnings that seem related are `Did not find catalog 'DEFAULT' to snapshot` before each Liquidbase migration. I think I'll wait for the dust to settle before testing this properly again!

**Closed** 2017-01-15 13:31 UTC
Labels: enhancement

**Comment by jxs** [comment] 2017-03-20 12:28
had to rollback from the new 6.2 version, besides being much more slow it's harder to configure behind a reverse proxy.
The context path isn't working, if you configure /music for example as the context path, login forwards to /login.
I totally agree with deprecating subsonic booter and generating subsonic as a jar file, but why embedding tomcat, instead of jetty which is much more lightweight?

**Comment by fxthomas** [comment] 2017-03-20 21:08
A complete reverse proxy documentation can be found [here](https://github.com/Libresonic/libresonic/blob/develop/documentation/PROXY.md). We should however, mention that some options like `contextPath` are now handled directly by Spring Boot and have thus changed names.

Re: performance, Tomcat's impact was mitigated as much as possible, but I'll be really interested if somebody manages to put Jetty back there while keeping Spring Boot working.

**Comment by biconou** [comment] 2017-03-20 22:37
Spring Boot + embedded jetty is worth testing.
I'm not disappointed by Libresonic performance has is.
Note that each transaction is slow only the first time it is ran.

**Comment by biconou** [comment] 2017-03-20 22:45
Spring Boot can also be used with another servlet container called Undertow.
