### ISSUE TITLE
Add Lighttpd proxy directions to PROXY.md

### ISSUE THREAD

**Issue by texneus** [Libresonic/libresonic#305] opened 2017-03-20 04:06 UTC
PROXY.md (in the development branch) currently lacks directions for a reverse proxy under Lighttpd.  It took me some time to figure it out because it seems you must also alter Tomcat, but this seems to work:

Tested on Lighttpd server service built into NAS4Free 11.0.0.4.3882 (FreeBSD 11-P7, Lighttpd 1.4.45) with Libresonic 6.1 and 6.2 Beta 1 in a virtual machine (jail) using Tomcat 8.  The following assumes https port will be 4443 and http port is 4040.

Current PROXY.md in the Tomcat section states:
Modify your <Connector> with the proper address and port:
```
<Connector 
    port="4040" 
    address="127.0.0.1"
    ...
```

~~Note that "address" is not a valid connector parameter per Tomcat8 documentation at https://tomcat.apache.org/tomcat-8.0-doc/config/http.html.  Adding it results in Tomcat not opening the port.~~  To make Tomcat work, ~~replace "address"~~ **append the connector block** with the following parameters so ~~the correct~~ **https** URLs are created.  If you are missing these parameters the URL will ~~be malformed~~**immediately revert to HTTP and the connection lost**.  I'm not sure if this is specific to Lighttpd or just an oversight in the current documentation. 

~~proxyName="<external IP/DNS address>"~~
~~proxyPort="4443"~~
`               scheme="https"`

In the Lighttpd configuration, add the following parameters:

```
server.modules += ("mod_proxy")
$SERVER["socket"] == ":4443" {
    ssl.engine  = "enable"
    ssl.pemfile = "<location of cert+key PEM file>"
    $HTTP["host"] == "<external IP/DNS address>" {
        proxy.server = ( "" => ( ("host" => "<IP address of Libersonic Server>", "port" => 4040) ) )
    }
}
```

The Lighttpd configuration is the minimum required for SSL.  Various enhancements are available, some interesting possibilities here: https://www.nas4free.org/forums/viewtopic.php?f=48&t=9421

In both of the above, <external IP/DNS address> is external address you will use to access Libresonic.  If you have a DNS service, then you probably want your DNS address.  < IP address of Libersonic Server> is the internal IP address of your server.  If the server and proxy are on the same machine then you can use "localhost" or "127.0.0.1".  The PEM file must contain both your SSL certificate and private key.

**Comment by muff1nman** [comment] 2017-03-20 05:34
Couple thoughts:

- Tomcat 8 does support address on the connector attribute and is listed in the link you gave.
- Adding proxyName and proxyPort seems like it should be irrelevant. The link suggests those modify getServerName and getServerPort which are not used by Libresonic.
- Please submit a PR to modify the documentation.

**Comment by texneus** [comment] 2017-03-21 01:00
Thoughts on your thoughts...

- Yes, you are correct!  I just needed to scroll down the page further.  Regardless Tomcat doesn't open a port if I add this line verbatim to the connector block.  After reading the Tomcat documentation my conclusion is this statement is not needed unless the server has multiple IP addresses, and when specified it defines which IP to open the port on.  Knowing that, I think it wants a real IP address and not "localhost" (wouldn't this cause Tomcat to listen to itself?).  That said, I still think it can "go away", or perhaps it's purpose clarified if a machine with multiple IPs are involved.  Do you concur?
- Upon further thought I figured this was probably also correct.  The issue I was seeing wasn't so much a malformed URL, but rather losing the HTTPS connection which caused Firefox to alter the URL to what it thought it should be doing.  Removing proxyName and proxyPort from server.xml does indeed function as expected, however scheme is still necessary.  I tried this with 6.2 beta 1, 6.1, and even 5.3-kang and none would proxy in Lighttpd without this.  My assumption therefore is that this is as expected (or an inherited bug), or since it's not in the docs currently it is an oversight or may be a unique Lighttpd requirement (or Lighttpd bug).
- PR as in a pull request?  Totally new territory to me, but then so is all of this!  Any tutorials, tips, or step by step directions?

**Comment by muff1nman** [comment] 2017-03-21 01:33
> Yes, you are correct! I just needed to scroll down the page further. Regardless Tomcat doesn't open a port if I add this line verbatim to the connector block. After reading the Tomcat documentation my conclusion is this statement is not needed unless the server has multiple IP addresses, and when specified it defines which IP to open the port on. Knowing that, I think it wants a real IP address and not "localhost". That said, I still think it can "go away", or perhaps it's purpose clarified if a machine with multiple IPs are involved. Do you concur?

That is not necessarily true. The reason for the explicit addition of the loopback address is to ensure that it is not possible to get to the libresonic server except from the same host. The idea is that you only want your proxy server serving connections on a publicly accessible interface, not the actual libresonic server.

> Upon further thought I figured this was probably also correct. The issue I was seeing wasn't so much a malformed URL, but rather losing the HTTPS connection which caused Firefox to alter the URL to what it thought it should be doing. Removing proxyName and proxyPort from server.xml does indeed function as expected, however scheme is still necessary. I tried this with 6.2 beta 1, 6.1, and even 5.3-kang and none would https proxy in Lighttpd without this. My assumption therefore is that this is as expected (or an inherited bug), or since it's not in the docs currently it is an oversight or may be a unique Lighttpd requirement (or Lighttpd bug).

Scheme is actually very similar. It modifies HttpServletRequest#getScheme, which should not be necessary. Basically, I would be very hesitant to add any tomcat configurations specific for Lighttpd. The biggest thing is to make sure Lighttpd is setting the proper headers as discussed in [PROXY.md](documentation/PROXY.md):

``` 
 - `X-Forwarded-Host`
   - Provides server name and optionally port in the case that the proxy is on a non-standard port
 - `X-Forwarded-Proto`
   - Tells Libresonic whether to craft an HTTP or HTTPS url
 - `X-Forwarded-Server`
   - This is only a fallback in the case that `X-Forwarded-Host` is not available
 ```
I used wireshark to verify this in nginx and apache.

> PR as in a pull request? Totally new territory to me, but then so is all of this! Any tutorials, tips, or step by step directions?
Yes, a pull request. I imagine there are a bunch of resources out there, but the general idea is to fork the repo into your own github repo. Make changes using git into your personal repo. Use github web interface to create a PR from your personal repo to here.

**Comment by muff1nman** [comment] 2017-03-21 01:40
Just curious, is there any reason you're using lighttpd over the other three proxies?

**Comment by texneus** [comment] 2017-03-21 04:31
Well, color me confused!  I went back and added the address parameter and now it works just fine??!??!!  I guess I mistyped something previously.  If you say it should be there then I'll leave it in and move on.

I agree, it certainly acts as though X-Forwarded-Proto in particular is not being passed through.  What's irritating is what little I can find says Lighttpd should be passing all those headers unless you specifically disable them.  Of course, that doesn't mean it is, it's just supposed to.  I am successfully HTTPS proxying Emby through Lighttpd.  Same machine, same instance of Lighttpd, same config, just a separate VM vs Libresonic.  So there is some anecdotal evidence Lighttpd is working as advertized.  Since Tomcat sits between Lighttpd and Libresonic, I figured Tomcat must be blocking them which is why I started looking there.  I take it that the other proxy's are confirmed working without adding scheme (etc) to the Tomcat connector block?

To answer your question, I want to use Lighttpd because I'm trying to run everything on NAS4Free (FreeBSD based) server which offers Lighttpd out of the box.  Said server also hosts both Emby and Libresonic (and likely soon, SageTV) in their own jails (a simplified virtual machine, if you will).  Previously I configured each jail individually for www access.  Our prior discussions on proxy's wised me up to the proxy approach so I'm pushing now in this direction.  Is there any reason I should not use lighttpd?

**Comment by muff1nman** [comment] 2017-03-21 04:47
Okay that makes sense. I was just curious why you settled on lighttpd.

What exactly are you running into? Can you show some of the failed URLs via the developer tab in your browser? I imagine the stream URLs would be the first thing you would notice.

Yes all of the other proxies have been confirmed to work as laid out in PROXY.md on the develop branch.

If I can find a half hour sometime this next week, I might be able to take a look at lighttpd, I know what to look for ;) Can you post your entire lighttpd config?

**Comment by gstrauss** [comment] 2017-03-21 05:22
FYI: lighttpd mod_proxy provides X-Forwarded-For and X-Forwarded-Proto.  For historical reasons, lighttpd provides (the non-standard) X-Host instead of the (also non-standard) Apache header X-Forwarded-Host.

If you are proxying for a single host, a simple workaround is to use mod_setenv setenv.add-request-header to set set X-Forwarded-Host to be the single vhost.  A slightly more complex workaround is to use mod_magnet and write a few lines of custom lua code.

**Comment by muff1nman** [comment] 2017-03-21 06:28
@gstrauss thanks for the info! @texneus can you give that a shot?

**Comment by texneus** [comment] 2017-03-22 02:29
@gstrauss I thought I found some documentation that it also forwarded the other headers but I cannot seem to find that now.  I did try to add X-Forwarded-Host as follows (the lighttpd documentation isn't exactly precise on where it belongs) and there was no change in behavior.
```
$SERVER["socket"] == ":4443" {
    ssl.engine  = "enable"
    ssl.pemfile = "<location of cert+key PEM file>"
    $HTTP["host"] == "<external IP/DNS address>" {
        setenv.add-request-header = ("X-Forwarded-Host" => "<external IP/DNS address>")
        proxy.server = ( "" => ( ("host" => "<IP address of Libersonic Server>", "port" => 4040) ) )
    }
}
```
I also tried this, which also had no effect...
`setenv.add-request-header = ("X-Forwarded-Proto" => "https")`

@muff1nman I'm not sure what you mean by development tab but attached is a screen grab & error.  URL obfuscated but you can still see what it does.  Basically if I try to login by going to https://xxx.yyy.zzz:4443/libresonic, the connection immediately reverts to standard htttp (xxx.yyy.zzz:4443/libresonic) and Firefox displays an error screen (The connection was reset).  Occasionally, but not always (not sure what triggers it), firefox will attempt to "fix" the URL settling on www.yyy.zzz:4443/libresonic before saying the URL cannot be found (or something similar).  So as you can see I get exactly nowhere as I cannot even log in.
![reset](https://cloud.githubusercontent.com/assets/23441049/24178834/93868cd4-0e79-11e7-9b39-911de648c430.jpg)

But, if I do nothing more than add the scheme parameter in Tomcat's server.xml connector statement
From:
```
    <Connector port="4040" protocol="HTTP/1.1"
               connectionTimeout="20000"
               address="127.0.0.1"/>
```
To:
```
    <Connector port="4040" protocol="HTTP/1.1"
               connectionTimeout="20000"
               scheme="https"
               address="127.0.0.1"/>
```
and it works.  I won't say it works 100% since I don't use all features, but I've been streaming music for hours at a time the past few days in DSub without issue.  I'm open to other suggestions, I'm pretty much at my wits end on this...

**Comment by texneus** [comment] 2017-03-22 02:44
@muff1nman as requested here is my **exact** and complete lighttpd configuration file.  I certainly welcome any insight you can add!  Only the final lines (starting with server.modules += ("mod_proxy")) is the configuration that I can define.  All the previous lines are the "out of the box" configuration and a switches from NAS4Free.  As stated previously I am currently HTTPS proxying TWO services, Emby and Libresonic.  Emby is working without any fuss, but isn't Tomcat/Java either (it runs on Mono).

As before my external URL is obfuscated, xxx.yyy.zzz refers to my external DNS name.  Also, I have indeed tried it without the extra SSL stuff...it doesn't seem to matter.

```
server.port = 80
server.username = "www"
server.groupname = "www"
server.document-root = "/mnt/Guide/www/webroot"
server.modules = (
  "mod_access",
  "mod_auth",
  "mod_expire",
  "mod_cgi",
  "mod_fastcgi",
  "mod_setenv",
  "mod_rewrite",
  "mod_redirect",
  "mod_alias"
 )
server.errorlog-use-syslog = "enable"
# debugmode debug.log-request-handling enable/disable
debug.log-request-handling = "disable"
#server.event-handler = "freebsd-kqueue"
server.event-handler = "libev"
server.max-write-idle = 360
index-file.names   = ( "index.php", "index.html", "index.htm", "index.shtml", "default.htm" )
# set trust path
setenv.add-environment = ( "PATH" => "/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin" )
#$HTTP["url"] =~ "\.(js|css|png|gif|jpg)$" {
#    expire.url = ( "" => "access plus 1 hours" )
#}
# mimetype mapping
mimetype.assign             = (
  ".pdf"          =>      "application/pdf",
  ".sig"          =>      "application/pgp-signature",
  ".spl"          =>      "application/futuresplash",
  ".class"        =>      "application/octet-stream",
  ".ps"           =>      "application/postscript",
  ".torrent"      =>      "application/x-bittorrent",
  ".dvi"          =>      "application/x-dvi",
  ".gz"           =>      "application/x-gzip",
  ".pac"          =>      "application/x-ns-proxy-autoconfig",
  ".swf"          =>      "application/x-shockwave-flash",
  ".tar.gz"       =>      "application/x-tgz",
  ".tgz"          =>      "application/x-tgz",
  ".tar"          =>      "application/x-tar",
  ".zip"          =>      "application/zip",
  ".mp3"          =>      "audio/mpeg",
  ".m3u"          =>      "audio/x-mpegurl",
  ".wma"          =>      "audio/x-ms-wma",
  ".wax"          =>      "audio/x-ms-wax",
  ".ogg"          =>      "application/ogg",
  ".wav"          =>      "audio/x-wav",
  ".gif"          =>      "image/gif",
  ".jar"          =>      "application/x-java-archive",
  ".jpg"          =>      "image/jpeg",
  ".jpeg"         =>      "image/jpeg",
  ".png"          =>      "image/png",
  ".svg"          =>      "image/svg+xml",
  ".xbm"          =>      "image/x-xbitmap",
  ".xpm"          =>      "image/x-xpixmap",
  ".xwd"          =>      "image/x-xwindowdump",
  ".css"          =>      "text/css",
  ".html"         =>      "text/html",
  ".htm"          =>      "text/html",
  ".js"           =>      "text/javascript",
  ".asc"          =>      "text/plain",
  ".c"            =>      "text/plain",
  ".cpp"          =>      "text/plain",
  ".log"          =>      "text/plain",
  ".conf"         =>      "text/plain",
  ".text"         =>      "text/plain",
  ".txt"          =>      "text/plain",
  ".spec"         =>      "text/plain",
  ".dtd"          =>      "text/xml",
  ".xml"          =>      "text/xml",
  ".mp4"          =>      "video/mp4",
  ".mpg4"         =>      "video/mp4",
  ".mpeg"         =>      "video/mpeg",
  ".mpg"          =>      "video/mpeg",
  ".mov"          =>      "video/quicktime",
  ".qt"           =>      "video/quicktime",
  ".avi"          =>      "video/x-msvideo",
  ".asf"          =>      "video/x-ms-asf",
  ".asx"          =>      "video/x-ms-asf",
  ".wmv"          =>      "video/x-ms-wmv",
  ".bz2"          =>      "application/x-bzip",
  ".tbz"          =>      "application/x-bzip-compressed-tar",
  ".tar.bz2"      =>      "application/x-bzip-compressed-tar",
  ".rpm"          =>      "application/x-rpm",
  # make the default mime type application/octet-stream.
  ""              =>      "application/octet-stream",
 )
url.access-deny = ( "~", ".inc", ".websrv_htpasswd" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )
server.pid-file = "/var/run/websrv.pid"
# cgi.assign = (".php" => "/usr/local/bin/php-cgi-websrv")
server.tag = "webserv"

# FastCGI
fastcgi.server = ( ".php" =>
  (( "socket" => "/var/tmp/php-wsrv.socket",
        "bin-path" => "/usr/local/bin/php-cgi",
        "bin-environment" => (
            "PHP_FCGI_CHILDREN" => "5",
            "PHP_FCGI_MAX_REQUESTS" => "1000"
        ),
        "bin-copy-environment" => (
            "PATH", "SHELL", "USER" ),
        "broken-scriptfilename" => "enable",
        "min-procs" => 1,
        "max-procs" => 2,
        "max-load-per-proc" => 90,
        "idle-timeout" => 360,
        "x-sendfile" => "enable"
    )
  )
)
server.upload-dirs = ( "/mnt/Guide/www/webroot" )
server.max-request-size = 16777216
# /mnt/Guide/www/genkey.sh to generate new pem files
server.modules += ("mod_proxy")
$SERVER["socket"] == ":8920" {
    ssl.engine  = "enable"
    ssl.use-sslv2 = "disable"
    ssl.use-sslv3 = "disable"
    ssl.pemfile = "/mnt/Guide/www/host.pem"
    ssl.dh-file = "/mnt/Guide/www/dhparam.pem"
    ssl.ec-curve = "secp384r1"
    ssl.use-compression = "disable"
    ssl.cipher-list = "EECDH+AESGCM:EDH+AESGCM:AES128+EECDH:AES128+EDH"
    $HTTP["host"] == "xxx.yyy.zzz" {
        proxy.server = ( "" => ( ("host" => "192.168.1.211", "port" => 8096) ) )
    }
}
$SERVER["socket"] == ":4443" {
    ssl.engine  = "enable"
    ssl.use-sslv2 = "disable"
    ssl.use-sslv3 = "disable"
    ssl.pemfile = "/mnt/Guide/www/host.pem"
    ssl.dh-file = "/mnt/Guide/www/dhparam.pem"
    ssl.ec-curve = "secp384r1"
    ssl.use-compression = "disable"
    ssl.cipher-list = "EECDH+AESGCM:EDH+AESGCM:AES128+EECDH:AES128+EDH"
    $HTTP["host"] == "xxx.yyy.zzz" {
#        setenv.add-request-header = ("X-Forwarded-Host" => "xxx.yyy.zzz")
#        setenv.add-request-header = ("X-Forwarded-Proto" => "https")
        proxy.server = ( "" => ( ("host" => "192.168.1.212", "port" => 4040) ) )
    }
}
```

**Comment by texneus** [comment] 2017-03-22 03:26
An interesting discovery and maybe a clue???  DSub on my phone network says the sever connection is OK, I can update libraries and cover art, and it will still stream.  Yet, when I open the web interface on my phone it does the same thing as I see on my local PC...https is dropped and it goes nowhere.

**Comment by muff1nman** [comment] 2017-03-23 00:40
The whole connection reset bit tells me the proxy isn't rewriting requests correctly. It needs to be configured to rewrite http to https. Yes you might be able to do this via the `scheme` settings on tomcat, however I dont advise it.

I tried setting this up myself, but the docs weren't clear on how to do it. As such, I don't think we can support lighttpd.

**Comment by texneus** [comment] 2017-03-23 03:09
What can I say other than great minds think alike!  I noticed the configurations for the other proxy's included this this afternoon and I'm trying to incorporate this into Lighttpd configuration this evening, but as you apparently noticed the Lighttpd documentation isn't exactly concise and example configs from others don't seem to be working for me either.  I'm seriously considering ditching this at this point and running HAProxy.  I remain hopeful though...

**Comment by gstrauss** [comment] 2017-03-23 04:36
The $HTTP["host"] must match what was sent in the HTTP "Host" header.  If you are running on a non-standard port, then your request will include the port.  Standard port for http is 80 and standard port for https is 443.  Your observation that your changes were not having any effect is likely because your requests are not being proxied. 
```
$SERVER["socket"] == ":4443" {
    ssl.engine  = "enable"
    ssl.pemfile = "<location of cert+key PEM file>"
    $HTTP["host"] == "<external IP/DNS address>:4443" {
        setenv.add-request-header = ("X-Forwarded-Host" => "<external IP/DNS address>")
        proxy.server = ( "" => ( ("host" => "<IP address of Libersonic Server>", "port" => 4040) ) )
    }
}
```
If you are going to forward all traffic received on port 4443 to your Libersonic server, then just use the simpler config:
```
$SERVER["socket"] == ":4443" {
    ssl.engine  = "enable"
    ssl.pemfile = "<location of cert+key PEM file>"
    setenv.add-request-header = ("X-Forwarded-Host" => "<external IP/DNS address>")
    proxy.server = ( "" => ( ("host" => "<IP address of Libersonic Server>", "port" => 4040) ) )
}
```

**Comment by gstrauss** [comment] 2017-03-23 04:42
@muff1nman, would you be more specific about what do you mean by rewriting requests?  lighttpd mod_proxy is a reverse proxy and forwards each request received by lighttpd to the backend via an HTTP1.0 request.  lighttpd mod_proxy modifies X-Forwarded-For, and adds/overwrites X-Host and X-Forwarded-Proto

**Comment by muff1nman** [comment] 2017-03-23 12:50
Biggest thing is that it doesn't seem to be rewriting the response redirects appropriately.  I.e. if the proxied host sends back a 302 to http://127.0.0.1/libresonic/login I would expect it to be rewritten as https://example.com:4443/libresonic/login. With that said, I have not tried adding :4443 to the host match.

**Comment by gstrauss** [comment] 2017-03-23 14:13
> Biggest thing is that it doesn't seem to be rewriting the response redirects appropriately.
That does not happen by magic.  That's a feature present on other servers (e.g. Apache ProxyPassReverse) that is not currently present in lighttpd mod_proxy.  There is an open feature request to add similar functionality to mod_proxy.

**Comment by muff1nman** [comment] 2017-03-23 15:20
Good to know. Do you happen to have a link to the feature request? Thanks for all your help @gstrauss

**Comment by gstrauss** [comment] 2017-03-23 16:38
https://redmine.lighttpd.net/issues/152 is the feature request lighttpd mod_proxy to support some of the features of Apache ProxyPass and ProxyPassReverse.

**Comment by muff1nman** [comment] 2017-03-24 01:31
@texneus, in light of that I think it makes sense to close this for now. We can reopen later if things change.

**Closed by muff1nman** 2017-03-24 01:31 UTC

**Comment by texneus** [comment] 2017-03-24 02:03
Concur.  Thanks for your help @gstrauss and the consideration @muff1nman!
