### ISSUE TITLE
Incorrect Album Count [MySQL 5.7.17]

### ISSUE THREAD

**Issue by texxasrulez** [Libresonic/libresonic#330] opened 2017-04-01 16:07 UTC
Version	6.2.beta2 – March 24, 2017
Server	Apache Tomcat/8.0.14 (Debian), java 1.8.0_121, Linux (95.9 MB / 123.8 MB)
 
I have an issue with Album count. It displays the same amount for songs as it does albums as shown below:

12 artists
595 albums
595 songs
4.31 GB
39 hours

This is a test machine so I have very little music on it at this point in time. I will keep plugging and testing this out. I have been a long time Subsonic user and am branching out. The external DB is a feature I want very much so I will help you out as much as I can to make this spot on.

Great Job and keep up the good work ...

**Comment by muff1nman** [comment] 2017-04-01 16:15
Interesting, seems it might be specific to your collection/setup. As I'm not seeing it on my server. What is the version of mysql that you ended up using?

**Comment by texxasrulez** [comment] 2017-04-01 18:46
I thought I put that on here. I am using mysql 5.7.17

**Comment by muff1nman** [comment] 2017-04-02 22:03
Yep see it now.

**Comment by muff1nman** [comment] 2017-04-04 00:20
I thought I was able to reproduce this, but actually I my test media wasn't tagged correctly. So with that in mind, is your library tagged correctly and can you run the following queries:

```
select count(distinct artist) from media_file where type = 'MUSIC';
select count(distinct album) from media_file where type = 'MUSIC';
```

**Comment by texxasrulez** [comment] 2017-04-04 05:50
My tags should be good. I have worked on them for years.

Running commands above give me the correct count for artist and album I have uploaded

**Comment by muff1nman** [comment] 2017-04-04 12:12
Its the album count which is incorrect, right? In that you do have 595 songs?

**Comment by muff1nman** [comment] 2017-04-04 12:35
I have a hunch this might actually be caused by the same thing that caused #319. You could try the latest from the develop branch or wait for the next release.

**Comment by muff1nman** [comment] 2017-04-08 16:48
I'm pretty confident this is a dup, so will close this, but feel free to reopen if the issue persists in 6.2.beta3

**Closed by muff1nman** 2017-04-08 16:48 UTC
Labels: bug

**Comment by texxasrulez** [comment] 2017-04-10 00:04
I can confirm this is working as expected now. Album count is correct after 6.2beta3
