### ISSUE TITLE
Render usernames non case-sensitive for LDAP authentication

### ISSUE THREAD

**Issue by DaveWut** [Libresonic/libresonic#99] opened 2016-05-30 16:04 UTC
In the file LibresonicLdapBindAuthenticator.java, function "authenticate(String username, String password)", do not allow Libresonic to create another local user when the user use alternate upper case or lower case characters in their username. 

By example, lets say someone has "testuser" as a username. The person logs in, then logs out. That same person try once again, but this time writes "TESTUSER" instead. This will create two local users. 

Line 61 is responsible for the retrieval of the user in the local database. This function should allow to make a character non-sensitive search.

**Comment by bajansen** [comment] 2016-06-01 20:25
If the local representation of users is character sensitive, fixing this bug will probably mean that either all usernames should be case insensitive, or that LDAP usernames should be limited to lowercase only.

**Comment by jolny** [comment] 2016-06-02 13:52
Can the method not simply convert the username to lowercase before doing anything else with it?

**Comment by bajansen** [comment] 2016-06-02 14:06
It can, but it means that the usernames will no longer be case sensitive as the username that will be looked up or created in the database will always be lowercase. Alternatively the LDAP function that calls for a username lookup could be modified to convert the username to lowercase before querying. In this case normal users will still be case sensitive, but users for which LDAP authentication is enabled will have to be lowercase only.

**Comment by DaveWut** [comment] 2016-06-02 17:17
This is exactly how I would do it. I would create a second signature of the function reponsible to retreive a local user, then add a boolean parameter named something like "nonCaseSensitive". The original function signature would still exist, so if it's used elsewhere, it doesn't break the app.

**Comment by bajansen** [comment] 2016-06-02 22:29
As LDAP itself is (generally) case insensitive, LDAP users in libresonic should be case insensitive as well. The problem is that you can't exactly do a case insensitive user lookup. You can however force case insensitivity by modifying the user lookup and create functions to convert the username to lowercase before looking it up or creating it in the database. 
Alternatively you could convert to lowercase in the LDAP authentication function before calling the username lookup which means that only LDAP users are case insensitive. This means however that users with capitals in their username that have been created in libresonic manually will not be able to use LDAP for authentication. I therefore think it's worth considering making all usernames case insensitive as having multiple users with the same name but with differing capitalization is confusing anyway.

**Comment by muff1nman** [comment] 2017-01-30 19:53
Resolved in develop.

**Closed by muff1nman** 2017-01-30 19:53 UTC
Labels: bug
