### ISSUE TITLE
Database legacy profil does not work on a fresh install

### ISSUE THREAD

**Issue by biconou** [Libresonic/libresonic#198] opened 2016-12-31 01:20 UTC
I've just merged the develop branch in the SpringBoot PR branch. 
Hey guys, that's a great job you made ! :+1: 

By default, the taken profil is "legacy". That's ok. 
But on a fresh install, where there is no existing database, it crashes. 
Liquibase seams to complain there is no /db/libresonic.lck file present.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [applicationContext-db.xml]: Invocation of init method failed; nested exception is liquibase.exception.DatabaseException: java.sql.SQLException: The database is already in use by another process: org.hsqldb.persist.NIOLockFile@497ae66d[file =/db/libresonic.lck, exists=false, locked=false, valid=false, fl =null]: java.io.FileNotFoundException: /db/libresonic.lck (Aucun fichier ou dossier de ce type)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) ~[spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) ~[spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.libresonic.player.boot.Application.main(Application.java:46) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:506) [spring-boot-maven-plugin-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
Caused by: liquibase.exception.DatabaseException: java.sql.SQLException: The database is already in use by another process: org.hsqldb.persist.NIOLockFile@497ae66d[file =/db/libresonic.lck, exists=false, locked=false, valid=false, fl =null]: java.io.FileNotFoundException: /db/libresonic.lck (Aucun fichier ou dossier de ce type)

```

**Comment by biconou** [comment] 2016-12-31 01:35
I fixed the problem by creating an initial libresonic.properties file containing.
```
database.config.type=embed
database.config.embed.driver=org.hsqldb.jdbcDriver
database.config.embed.url=jdbc:hsqldb:file:/var/libresonic/db/libresonic
database.config.embed.username=sa
database.config.embed.password=
```

Ok but : 

wouldn't it be better to consider that, if there is absolutely no libresonic.properties (thus no previous install) and the user did not created one to choose some kind of database, a default libresonic.properties should be created with the snippet below ? 
Hence if the user has no idea of how to configure a database, he will have a working libresonic out of the box using and embedded database persisted on disk.

**Comment by muff1nman** [comment] 2016-12-31 02:53
It should work without the properties file in place, is this in the develop branch or in the spring boot branch you encountered this?

**Comment by biconou** [comment] 2016-12-31 11:10
Both.

**Comment by biconou** [comment] 2016-12-31 13:24
I made some tests again and that's very strange. I got different behaviors from time to time. 
I must investigate more.

**Comment by muff1nman** [comment] 2016-12-31 16:57
I was able to reproduce this. It looks like this happens only when you do not have libresonic.home defined in your java properties.

**Comment by muff1nman** [comment] 2016-12-31 17:13
Should be fixed now.

**Closed by muff1nman** 2016-12-31 17:13 UTC

**Comment by biconou** [comment] 2016-12-31 18:35
That's fine. Even on Spring Boot branch.
