### ISSUE TITLE
"Failed to list children" errors

### ISSUE THREAD

**Issue by cascooscuro** [Libresonic/libresonic#285] opened 2017-03-10 18:08 UTC
Hi
I'm Using: 
Version	6.2.beta1 – March 5, 2017
Server	Apache Tomcat/8.0.41, java 1.8.0_121, Linux (448.3 MB / 940.5 MB)

I'm seeing a bunch of this erros:

 WARN FileUtil - Failed to list children for Led Zeppelin - Houses of the Holy (Super Deluxe Edition) - 2014 - FLAC/CD1/06 D???yer Mak???er.flac
WARN FileUtil - Failed to list children for /media/silvHD/pth/WM2/523631/Abdullah Ibrahim & Johnny Dyani - Good News from Africa (1973)/06 Moniebah???The Pilgrim .flac

Files in the directory are:

 06 D’yer Mak’er.flac
 06 Moniebah／The Pilgrim 

It looks like some  Unicode Characters like 'RIGHT SINGLE QUOTATION MARK' (U+2019) or Unicode  'FULLWIDTH SOLIDUS' (U+FF0F) are causing some issues with my setup.

Probably related to:
https://github.com/Libresonic/libresonic/issues/207
https://github.com/Libresonic/libresonic/issues/170

**Comment by texneus** [comment] 2017-03-10 21:20
I've had issues with non-ascii file names since pretty much forever, this is almost certainly a hold over from subsonic.  If you change the quotes to straight quotes and remove the slash (maybe replace it with a dash), it should work and get you by until a fix is issued.

**Comment by jooola** [comment] 2017-03-11 12:28
Related to #135
The #135 issue will prolly fix this !

**Comment by muff1nman** [comment] 2017-03-12 01:22
I would love to fix this, and I've tried several times to reproduce this, but haven't had any luck. I added a test that I thought should reproduce the issue, however it works fine on my machine. It would be great if someone could help reproduce this issue. Either clone the latest develop branch and run the following:
```
mvn -Dtest=org.libresonic.player.service.MediaScannerServiceTestCase#testSpecialCharactersInFilename -DfailIfNoTests=false test
```
Or provide detailed instructions using something reproducible like a docker build.

**Comment by jooola** [comment] 2017-03-12 03:32
@cascooscuro  Please provide more infos about you're configuration !
System , step to install version of the programms you use ! weel every thing ! I see we can't reproduce you're issue so give the more you can !

**Comment by muff1nman** [comment] 2017-03-12 05:59
@joola I understand you want to help, but please let someone knowledgeable deal with these bug reports.

**Comment by cascooscuro** [comment] 2017-03-13 13:58
Running:

`mvn -Dtest=org.libresonic.player.service.MediaScannerServiceTestCase#testSpecialCharactersInFilename -DfailIfNoTests=false test
`

resulted in all test passed:

[INFO] Libresonic ........................................ SUCCESS [0.124s]
[INFO] Libresonic REST API ............................... SUCCESS [1.642s]
[INFO] Sonos API ......................................... SUCCESS [1.163s]
[INFO] Libresonic Main ................................... SUCCESS [15.844s]

So I started  looking at issues with my env.
My locale was:

LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=es_ES.UTF-8
LC_TIME=es_ES.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=es_ES.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=es_ES.UTF-8
LC_NAME=es_ES.UTF-8
LC_ADDRESS=es_ES.UTF-8
LC_TELEPHONE=es_ES.UTF-8
LC_MEASUREMENT=es_ES.UTF-8
LC_IDENTIFICATION=es_ES.UTF-8
LC_ALL=


After adding:
`env LC_ALL=en_US.UTF-8`

to my /etc/init/tomcat.conf

the issues have disappeared.

So @muff1nman, you could try to fiddle with you locale and see if you can reproduce the issue with your setup.

Thanks all for your help!!

**Comment by muff1nman** [comment] 2017-03-13 14:22
Interesting, that's super helpful @cascooscuro. Just some further notes:

Adding LC_ALL=C will make the test fail:
```
LC_ALL=C mvn -Dtest=org.libresonic.player.service.MediaScannerServiceTestCase#testSpecialCharactersInFilename -DfailIfNoTests=false test
```

My (working) locale is similar to yours:

```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
I wonder if its not your locale on your box, but rather some tomcat problem.

In either case, its sounding like this isn't a code change as much as it is correct documentation of locale setup.

**Comment by cascooscuro** [comment] 2017-03-13 14:53
@muff1nman, these two gave some hints:
http://www.jvmhost.com/articles/locale-breaks-unicode-utf-8-java-tomcat/
http://stackoverflow.com/questions/11343828/file-encoding-has-no-effect-lc-all-environment-variable-does-it

As you say, this may be some nasty interaction of my locale and tomcat.

**Comment by muff1nman** [comment] 2017-03-20 01:56
Lets keep an eye on issues similar to this, but I think we can close this one for now.

**Closed by muff1nman** 2017-03-20 01:56 UTC
