### ISSUE TITLE
Apache httpd proxy not creating external urls correctly

### ISSUE THREAD

**Issue by gerroon** [Libresonic/libresonic#414] opened 2017-05-18 16:27 UTC
Hi

The "http:" portion of a stream url is missing wHen I choose "external player with playlist" for my player,

"//myurl.com:880/libresonic/stream?player=9&id=89294&suffix=.mp3"

As you see http: is missing from the url. Therefor the player cant play this playlist/song.

I am using Apache proxy with Tomcat and here is the settings.

        SSLEngine On
        SSLProxyEngine on
        SSLCertificateFile /etc/certs/rsa_III/server.pem
        SSLCertificateKeyFile  /etc/certs/rsa_III/server.key
 
        ProxyRequests Off
        ProxyPreserveHost Off
        
        RewriteEngine On
        RewriteCond %{REQUEST_URI} ^/$
        RewriteRule ^(.*)$ https://%{HTTP_HOST}$1/ [R=301,L]

        ProxyPass /libresonic/ http://0.0.0.0:8080/libresonic/

        ProxyPassReverse /libresonic/ http://0.0.0.0:8080/libresonic/
        

This current setup works fine with Dsub, so Dsub has no issues streaming from the server. I am not sure how this works but playlists are generated improperly.

Thanks

**Comment by mdecker** [comment] 2017-05-18 20:14
If a URL starts with "//" then it means that the client should choose the same protocol (http or https) it used for the source document.
 I guess if it works depends somewhat on your external player and how you feed the playlist to it: saving the playlist might not work, referencing it from a http or https server *should* work.

There is a discussion about the whole thing here, for example: http://stackoverflow.com/questions/4831741

**Comment by gerroon** [comment] 2017-05-18 21:28
@mdecker 

The url I gave you is straight from the .pls from LS. Even if missing http is ok, I do not think that having doubles slashes "//" at the beginning is a proper url to me.


For instances 

"//cnn.com"  resolves to "file:////cnn.com" in my browser.

**Comment by muff1nman** [comment] 2017-05-18 21:32
`//` aren't right. Have you tried the example config? This one looks different than the example

**Comment by gerroon** [comment] 2017-05-18 22:09
@muff1nman 

Which example?

**Comment by muff1nman** [comment] 2017-05-18 22:50
https://github.com/Libresonic/documentation/blob/stable/proxy.md

**Comment by muff1nman** [comment] 2017-05-18 22:50
We're kinda in the middle of construction on the docs so apologies if it wasn't clear

**Comment by gerroon** [comment] 2017-05-18 22:59
@muff1nman 

Thanks I will try it

**Comment by gerroon** [comment] 2017-05-18 23:11
@muff1nman 

Hi

I still have the exact same issue.


I am using Debian Wheezy 32bit Tomcat8 Libresonic 6.2


        SSLEngine On
        SSLProxyEngine on
        SSLCertificateFile /etc/certs/rsa_III/server.pem
        SSLCertificateKeyFile  /etc/certs/rsa_III/server.key

        ServerName xxxxx.com

        ProxyPass /libresonic/ http://0.0.0.0:8080/libresonic/
        ProxyPassReverse /libresonic/ http://0.0.0.0:8080/libresonic/
        
        ErrorLog /var/log/apache2/libresonic_error.log
        CustomLog /var/log/apache2/libresonic_access.log combined

**Comment by gerroon** [comment] 2017-05-18 23:21
I even tried this after enabling Mod Substitude

Substitute "s|//|http://|i"

**Comment by muff1nman** [comment] 2017-05-18 23:22
Why are you using `0.0.0.0`? Try `localhost` or `127.0.0.1`

**Comment by gerroon** [comment] 2017-05-18 23:29
That did not make a difference either.

**Comment by muff1nman** [comment] 2017-05-18 23:32
Everything else is working besides the external player?

**Comment by muff1nman** [comment] 2017-05-18 23:37
If so, it sounds like this is something we need to look into. Sorry I dont think I read your issue closely enough and didnt realize it was just a problem with the external player.

**Comment by muff1nman** [comment] 2017-05-18 23:51
Reproduced.

**Comment by muff1nman** [comment] 2017-05-18 23:52
Nginx config works if you're interested in a work around

**Comment by gerroon** [comment] 2017-05-19 00:12
@muff1nman 

Dsub works no isue there. 

I do not have Nginx so I will wait for the fix I guess. What is the issue?

**Comment by muff1nman** [comment] 2017-05-19 00:32
Can you try adding this:
```
RequestHeader set X-Forwarded-Proto "http"
```

Replace http with https if youre front end is ssl.

**Comment by gerroon** [comment] 2017-05-19 01:21
@muff1nman 

That fixes the url. But streaming does not seem to work at all ;( All the players I tried (vlc, smplayer, mpv) have problem playing any of the songs. The weird thing is that they cant play from the actual Libresonic's non proxy urls that runs on :8080


Here is a log from mpv trying to stream from actual Libresonic server (non Apache proxy)

    mpv "http://192.168.xx.xx:8080/libresonic/stream?player=9&id=89299&suffix=.mp3"
    Playing: http://192.168.xx.xx:8080/libresonic/stream?player=9&id=89299&suffix=.mp3
    [ytdl_hook] ERROR: Unsupported URL: http://192.168.2.133:8080/libresonic/login
    [ytdl_hook] youtube-dl failed, trying to play URL directly ... 
    Failed to recognize file format.


    Exiting... (Errors when loading file)

**Comment by muff1nman** [comment] 2017-05-19 01:39
@gerroon. Let's create a different issue for other issues.

**Comment by mdecker** [comment] 2017-05-19 06:02
Seriously, have any of you read the link I provided? This is most likely not a mistake - even if it might have unintended consequences.
The links in the playlist are protocol-agnostic and the client is supposed to substitute the protocol that it used to access the playlist in the first place. This avoids protocol-guessing on the server side as the client should choose the correct protocol automatically.

As I already said before: This won't work if you save the playlist to a file. But it should work if you give the playlist URL to your player - except if the player's web client code is not RFC compliant.
This is why @gerroon's example entering "//cnn.com" into a browser is absolutely not the point. If you had a web page (NOT locally opened via "file://"!) that referenced "//cnn.com" in a link, your browser would try to send you to either the HTTP or the HTTPS version depending on how you accessed the site containing the link.

@gerroon how do you feed the playlist into vlc or other players? Did you save it to a file?

**Comment by muff1nman** [comment] 2017-05-19 06:18
@mdecker it's a bug (not intentional ;). It's should have a http(s) protocol as that's only what libresonic listens on and should be present in any external links we generate.

**Comment by mdecker** [comment] 2017-05-19 06:40
I still disagree regarding it being a bug. ;)
Anyway, if you "fix" it, then you have to make sure you always choose the right protocol behind a proxy. The current way spares you that.

**Comment by jooola** [comment] 2017-05-19 08:14
About the streaming issue, this may be duplicate of #371.
I don't think so but maybe !

**Comment by gerroon** [comment] 2017-05-19 14:43
@mdecker 

I saved the playlist  and opened it in VLC. DIrectly opening in VLc is same to it just opens the saved file.  LS creates a file, it does not give me a streaming playlist url like Ampache does.

**Comment by muff1nman** [comment] 2017-05-20 15:00
@gerroon I believe the single streaming url is possible with the "External Player" option, however I couldn't get it working yesterday, so there might be an issue there as well.

**Comment by muff1nman** [comment] 2017-05-20 15:19
The documentation was updated so am closing this.

**Closed by muff1nman** 2017-05-20 15:19 UTC
Labels: accepted, bug
